version: 2
updates:
  - package-ecosystem: npm
    groups:
      patch:
        group-by: dependency-name
        update-types:
          - "patch"
      update:
        group-by: dependency-name
        update-types:
          - "minor"
    directory: "/"
    ignore:
      - update-types:
          - version-update:semver-major
        dependency-name: '*'
      - update-types:
          - version-update:semver-major
          - version-update:semver-minor
        dependency-name: next
      - update-types:
          - version-update:semver-major
          - version-update:semver-minor
        dependency-name: react
      - update-types:
          - version-update:semver-major
          - version-update:semver-minor
        dependency-name: "react-*"
      - update-types:
          - version-update:semver-major
          - version-update:semver-minor
        dependency-name: "@nrwl/*"
    exclude-paths:
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/public/**"
      - "**/tmp/**"
      - "**/coverage/**"
      - "**/logs/**"
      - "**/cache/**"
      - "**/temp/**"
      - "**/.next/**"
      - "**/.swc/**"
      - "**/.cache/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    groups:
      patch:
        group-by: dependency-name
        update-types:
          - "patch"
      update:
        group-by: dependency-name
        update-types:
          - "minor"
      breaking:
        group-by: dependency-name
        update-types:
          - "major"
    directory: "/python"
    exclude-paths:
      - "**/__pycache__/**"
      - "**/.pytest_cache/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10